name: test-java
on:
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Obtenemos codigo / chequeamos repositorio
      uses: actions/checkout@v2

    - name: Configurar java - temurin jdk 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: test al proyecto
      run: |
        ./mvnw test